REPO_CREATOR_CONFIGS:
    PROJECTS_DIR: "" # Directory where your projects are stored
    TEMPLATES_DIR: "" 
    GITHUB_USERNAME: ""
    GITHUB_ACCESS_TOKEN: "" # Github PAT (Personal Access Token)

    # For more information regarding the creation of a PAT, see - 
    # https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

